name: Discord Notification

on:
  push:
    branches:
      - "*"

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract commit information and send Discord message
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          AUTHOR=$(git log -1 --pretty=format:'%an')
          AUTHOR_USERNAME=$(echo "${{ github.event.head_commit.author.username }}")
          BRANCH=$(echo ${{ github.ref }} | awk -F'/' '{print $NF}')
          REPO_NAME=$(echo ${{ github.repository }} | awk -F'/' '{print $NF}')
          COMMIT_URL="${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          JSON_PAYLOAD=$(cat <<EOF
          {
            "embeds": [{
              "title": "Repositorio: $REPO_NAME",
              "url": "$COMMIT_URL",
              "color": 3447003,
              "fields": [
                {
                  "name": "Mensaje del commit",
                  "value": "\`\`\`$COMMIT_MESSAGE\`\`\`"
                },
                {
                  "name": "Rama",
                  "value": "\`$BRANCH\`",
                  "inline": true
                }
              ],
              "author": {
                "name": "$AUTHOR",
                "icon_url": "https://avatars.githubusercontent.com/u/$AUTHOR_USERNAME?v=4"
              },
              "footer": {
                "text": "GitHub Actions",
                "icon_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
              },
              "timestamp": "$TIMESTAMP"
            }]
          }
          EOF
          )

          curl -H "Content-Type: application/json" -d "$JSON_PAYLOAD" $DISCORD_WEBHOOK